# Use an official Python runtime as a parent image
FROM python:3.10.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libgomp1 \
 && rm -rf /var/lib/apt/lists/*

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements_api.txt
RUN pip install --no-cache-dir -r requirements_api.txt

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Define environment variable to improve Python logging (optional)
ENV PYTHONUNBUFFERED=1

# Run app.py using Gunicorn when the container launches
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "app:app"]
